/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2rIyCjl0XA7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@repo/ui/components/ui/card"
import { Label } from "@repo/ui/components/ui/label"
import { Input } from "@repo/ui/components/ui/input"
import { Textarea } from "@repo/ui/components/ui/textarea"
import { Button } from "@repo/ui/components/ui/button"

export function Editor() {
  return (
    <div className="flex flex-col w-full min-h-screen bg-background text-foreground dark:bg-[#1a1b1e] dark:text-white">
      <main className="flex flex-1 p-4 md:p-10">
        <div className="flex flex-col w-full gap-4 md:flex-row">
          <div className="w-full md:w-1/2">
            <h1 className="text-3xl font-bold">Experience</h1>
            <Card className="mt-4">
              <CardHeader className="flex items-center justify-between">
                <div>
                  <CardTitle>Flipkart</CardTitle>
                  <CardDescription>Senior UX Researcher</CardDescription>
                </div>
                <div className="text-sm text-muted-foreground dark:text-white">Jun 2022 - Jul 2023</div>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="company">Company</Label>
                  <Input id="company" placeholder="Company" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="role">Role</Label>
                  <Input id="role" placeholder="Role" />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="start-date">Start Date</Label>
                    <Input id="start-date" placeholder="Start Date" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="end-date">End Date</Label>
                    <Input id="end-date" placeholder="End Date" />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="about-role">About the role</Label>
                  <Textarea
                    id="about-role"
                    placeholder="Include Situation, Task, Action and Result in your experience for better results"
                    className="min-h-[100px]"
                  />
                </div>
                <div className="flex items-center space-x-2">
                  <FilePenIcon className="w-5 h-5" />
                  <Button
                    variant="secondary"
                    size="sm"
                    className="bg-gradient-to-r from-purple-500 to-blue-500 text-white"
                  >
                    Fix Grammar
                  </Button>
                  <Button
                    variant="secondary"
                    size="sm"
                    className="bg-gradient-to-r from-purple-500 to-blue-500 text-white"
                  >
                    Shorten
                  </Button>
                  <Button
                    variant="secondary"
                    size="sm"
                    className="bg-gradient-to-r from-purple-500 to-blue-500 text-white"
                  >
                    Expand
                  </Button>
                  <Button
                    variant="secondary"
                    size="sm"
                    className="bg-gradient-to-r from-purple-500 to-blue-500 text-white"
                  >
                    Show Impact
                  </Button>
                  <Button
                    variant="secondary"
                    size="sm"
                    className="bg-gradient-to-r from-purple-500 to-blue-500 text-white"
                  >
                    Suggest Bullet
                  </Button>
                </div>
              </CardContent>
              <CardFooter className="flex justify-between">
                <Button variant="destructive">Delete</Button>
                <Button>Save</Button>
              </CardFooter>
            </Card>
            <Button variant="outline" className="mt-4">
              + Add experience
            </Button>
          </div>
          <div className="w-full md:w-1/2">
            <div className="flex items-center justify-between">
              <h2 className="text-xl font-bold">Select Template</h2>
              <Button>Download</Button>
            </div>
            <div
              className="mt-4 p-4 bg-white dark:bg-[#1a1b1e] rounded-md shadow-md border border-gray-200 dark:border-gray-700"
              style={{ maxWidth: "210mm", maxHeight: "297mm" }}
            >
              <h3 className="text-center text-xl font-bold dark:text-white">Enji Kusnadi</h3>
              <p className="text-center text-sm text-muted-foreground dark:text-white">
                Front-end Developer / UI/UX Designer
              </p>
              <div className="mt-4">
                <h4 className="text-lg font-semibold dark:text-white">Education</h4>
                <ul className="list-disc pl-5 space-y-1 dark:text-white">
                  <li>STMIK Indonesia Mandiri - Teknik Informatika (S1) - 2016 - present</li>
                </ul>
              </div>
              <div className="mt-4">
                <h4 className="text-lg font-semibold dark:text-white">Experience</h4>
                <ul className="list-disc pl-5 space-y-1 dark:text-white">
                  <li>Freelance 2018-2021 - Front-End Developer</li>
                  <li>PT. XYZ 2021-present - Front-End Developer</li>
                </ul>
              </div>
              <div className="mt-4">
                <h4 className="text-lg font-semibold dark:text-white">Featured Project</h4>
                <p className="dark:text-white">SPKGS - A system for managing goods and services procurement.</p>
              </div>
              <div className="mt-4">
                <h4 className="text-lg font-semibold dark:text-white">Skills & Tools</h4>
                <ul className="list-disc pl-5 space-y-1 dark:text-white">
                  <li>HTML, CSS, JavaScript, React</li>
                  <li>Figma, Sketch, Adobe XD</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

function FilePenIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22h6a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v10" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10.4 12.6a2 2 0 1 1 3 3L8 21l-4 1 1-4Z" />
    </svg>
  )
}


function XIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
