"use client"
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2rIyCjl0XA7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@repo/ui/components/ui/card"
import { Label } from "@repo/ui/components/ui/label"
import { Input } from "@repo/ui/components/ui/input"
import { Textarea } from "@repo/ui/components/ui/textarea"
import { Button } from "@repo/ui/components/ui/button"
import Resume, { ResumeProps } from "./Resume"
import { useState, useEffect } from "react"
import jsPDF from "jspdf"
import html2canvas from 'html2canvas';


export function Editor() {
  const [resumeData, setResumeData] = useState<ResumeProps>({
    name: "Dianne Russell",
    title: "UI/UX Designer",
    contact: {
      website: "diannerussell.art",
      email: "hello@diannerussell.com",
      phone: "(629) 555-0129"
    },
    bio: "I'm a ui/ux Designer with over 8 years of experience and a focus on branding, motion graphic, videography, and photography. I have expertise that is already an expert in the field of making digital product designs, such as applications and websites and I can also implement designs into wordpress",
    education: [
      {
        institution: "Liceria University",
        years: "2009 - 2012",
        degree: "Bachelor of Computer Technology"
      },
      {
        institution: "Oxford University",
        years: "2012 - 2015",
        degree: "Master of Computer Science - Software Engineering"
      }
    ],
    experience: [
      {
        company: "Facebook",
        role: "Lead UI/UX Designer",
        duration: "SEP 2022 - PRESENT",
        responsibilities: [
          "Led the design direction and created custom UI assets using Figma and Adobe CC, from wireframes to high fidelity interactions",
          "Managed numerous cross-discipline workshops to communicate design intentions and manage expectations across teams"
        ]
      }
    ],
    skills: {
      "UI/UX Design": ["User Research", "Wireframing", "Prototyping"],
      "Development": ["JavaScript", "TypeScript", "React"]
    },
    achievement: {
      title: "Bestfolios, 2022",
      description: "Editor's Pick for Best Design Portfolio"
    }
  });

  useEffect(() => {
    const savedData = localStorage.getItem('resumeData');
    if (savedData) {
      setResumeData(JSON.parse(savedData));
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('resumeData', JSON.stringify(resumeData));
  }, [resumeData]);

  const handleDownload = () => {
    const element = document.querySelector("#resume")!;
  
    html2canvas(element, {
      scale: 4, // Increase scale for better quality
      logging: false,
      useCORS: true,
      windowWidth: element.scrollWidth,
      windowHeight: element.scrollHeight
    }).then(canvas => {
      const imgData = canvas.toDataURL('image/png');
  
      // A4 size in pt (1pt = 1/72 inch)
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'pt',
        format: 'a4'
      });
  
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
  
      const widthRatio = pageWidth / canvas.width;
      const heightRatio = pageHeight / canvas.height;
      const ratio = widthRatio > heightRatio ? heightRatio : widthRatio;
  
      const canvasWidth = canvas.width * ratio;
      const canvasHeight = canvas.height * ratio;
  
      const marginX = (pageWidth - canvasWidth) / 2;
      const marginY = (pageHeight - canvasHeight) / 2;
  
      pdf.addImage(imgData, 'PNG', marginX, marginY, canvasWidth, canvasHeight, undefined, 'FAST');
  
      pdf.save("resume.pdf");
    });
  };
  const handleInputChange = (section: keyof ResumeProps, field: string, value: any, index?: number, category?: string) => {
    setResumeData((prevData) => {
      if (section === 'experience' || section === 'education') {
        const updatedSection = [...prevData[section]!];
        updatedSection[index!] = { ...updatedSection[index!], [field]: value };
        return { ...prevData, [section]: updatedSection };
      } else if (section === 'skills') {
        const updatedSkills = { ...prevData.skills };
        if (index !== undefined && category) {
          const updatedCategorySkills = [...(updatedSkills[category] || [])];
          if (field === 'newSkill') {
            updatedCategorySkills.push(value);
          } else if (field === 'deleteSkill') {
            updatedCategorySkills.splice(index, 1);
          }
          updatedSkills[category] = updatedCategorySkills;
        } else if (field === 'newCategory') {
          updatedSkills[value] = [];
        }
        return { ...prevData, skills: updatedSkills };
      } else if (typeof prevData[section] === 'object' && prevData[section] !== null) {
        return {
          ...prevData,
          [section]: {
            ...prevData[section],
            [field]: value
          }
        };
      } else {
        return {
          ...prevData,
          [section]: value
        };
      }
    });
  };

  const handleAddField = (section: keyof ResumeProps) => {
    if (section === 'skills') {
      handleInputChange('skills', 'newCategory', 'New Category');
    } else if (section === 'experience' || section === 'education') {
      setResumeData((prevData) => {
        const updatedSection = [...prevData[section]!, {}];
        return { ...prevData, [section]: updatedSection };
      });
    } else if (section === 'achievement') {
      setResumeData((prevData) => ({ ...prevData, achievement: { title: '', description: '' } }));
    }
  };

  const handleDeleteField = (section: keyof ResumeProps, index?: number, category?: string) => {
    if (section === 'experience' || section === 'education') {
      setResumeData((prevData) => {
        const updatedSection = prevData[section]?.filter((_, i) => i !== index);
        return { ...prevData, [section]: updatedSection };
      });
    } else if (section === 'skills' && category) {
      const updatedSkills = { ...resumeData.skills };
      delete updatedSkills[category];
      setResumeData((prevData) => ({ ...prevData, skills: updatedSkills }));
    } else if (section === 'achievement') {
      setResumeData((prevData) => ({ ...prevData, achievement: undefined }));
    }
  };

  return (
    <div className="flex flex-col w-full min-h-screen bg-background text-foreground dark:bg-[#1a1b1e] dark:text-white">
      <main className="flex flex-1 p-4 md:p-10">
        <div className="flex flex-col w-full gap-4 md:flex-row">
          <div className="w-full md:w-1/2">
            <h1 className="text-3xl font-bold">Edit Resume</h1>
            
            <div className="mt-8">
              <h2 className="text-2xl font-semibold">Personal Info</h2>
              <div className="mt-4">
                <Label htmlFor="name">Name</Label>
                <Input
                  id="name"
                  value={resumeData.name || ''}
                  onChange={(e) => handleInputChange('name', 'name', e.target.value)}
                  placeholder="Name"
                />
                <Label htmlFor="title">Title</Label>
                <Input
                  id="title"
                  value={resumeData.title || ''}
                  onChange={(e) => handleInputChange('title', 'title', e.target.value)}
                  placeholder="Title"
                />
                <Label htmlFor="website">Website</Label>
                <Input
                  id="website"
                  value={resumeData.contact?.website || ''}
                  onChange={(e) => handleInputChange('contact', 'website', e.target.value)}
                  placeholder="Website"
                />
                <Label htmlFor="email">Email</Label>
                <Input
                  id="email"
                  value={resumeData.contact?.email || ''}
                  onChange={(e) => handleInputChange('contact', 'email', e.target.value)}
                  placeholder="Email"
                />
                <Label htmlFor="phone">Phone</Label>
                <Input
                  id="phone"
                  value={resumeData.contact?.phone || ''}
                  onChange={(e) => handleInputChange('contact', 'phone', e.target.value)}
                  placeholder="Phone"
                />
                <Label htmlFor="bio">Bio</Label>
                <Textarea
                  id="bio"
                  value={resumeData.bio || ''}
                  onChange={(e) => handleInputChange('bio', 'bio', e.target.value)}
                  placeholder="Bio"
                  className="min-h-[100px]"
                />
              </div>
            </div>

            <div className="mt-8">
              <h2 className="text-2xl font-semibold">Experience</h2>
              {resumeData.experience?.map((exp, index) => (
                <Card className="mt-4" key={index}>
                  <CardHeader className="grid justify-items-stretch">
                    <div>
                      <CardTitle>
                        <Input 
                          value={exp.company || ''}
                          onChange={(e) => handleInputChange('experience', 'company', e.target.value, index)}
                          placeholder="Company"
                        />
                      </CardTitle>
                      <CardDescription>
                        <Input 
                          value={exp.role || ''}
                          onChange={(e) => handleInputChange('experience', 'role', e.target.value, index)}
                          placeholder="Role"
                        />
                      </CardDescription>
                    </div>
                    <div className="text-sm text-muted-foreground dark:text-white">
                      <Input 
                        value={exp.duration || ''}
                        onChange={(e) => handleInputChange('experience', 'duration', e.target.value, index)}
                        placeholder="Duration"
                      />
                    </div>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="grid gap-2">
                      {exp.responsibilities?.map((resp, respIndex) => (
                        <Input
                          key={respIndex}
                          value={resp || ''}
                          onChange={(e) => handleInputChange('experience', 'responsibilities', e.target.value, index, respIndex.toString())}
                          placeholder="Responsibility"
                        />
                      ))}
                      <Button variant="secondary" onClick={() => handleInputChange('experience', 'responsibilities', '', index)}>Add Responsibility</Button>
                    </div>
                  </CardContent>
                  <CardFooter className="grid gap-2">
                    <Button variant="destructive" onClick={() => handleDeleteField('experience', index)}>Delete</Button>
                  </CardFooter>
                </Card>
              ))}
              <Button variant="secondary" className="mt-4" onClick={() => handleAddField('experience')}>Add Experience</Button>
            </div>

            <div className="mt-8">
              <h2 className="text-2xl font-semibold">Skills</h2>
              {Object.keys(resumeData.skills || {}).map((category, catIndex) => (
                <Card className="mt-4" key={catIndex}>
                  <CardHeader className="grid justify-items-stretch">
                    <div>
                      <CardTitle>{category}</CardTitle>
                    </div>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    {(resumeData.skills[category] || []).map((skill, skillIndex) => (
                      <div className="grid grid-cols-12 gap-4" key={skillIndex}>
                        <div className="col-span-10">
                          <Input 
                            value={skill || ''}
                            onChange={(e) => handleInputChange('skills', '', e.target.value, skillIndex, category)}
                            placeholder="Skill"
                          />
                        </div>
                        <div className="col-span-2 flex items-center justify-end">
                          <Button variant="destructive" onClick={() => handleInputChange('skills', 'deleteSkill', '', skillIndex, category)}>Delete</Button>
                        </div>
                      </div>
                    ))}
                    <Button variant="secondary" onClick={() => handleInputChange('skills', 'newSkill', '', undefined, category)}>Add Skill</Button>
                  </CardContent>
                  <CardFooter className="grid gap-2">
                    <Button variant="destructive" onClick={() => handleDeleteField('skills', undefined, category)}>Delete Category</Button>
                  </CardFooter>
                </Card>
              ))}
              <Button variant="secondary" className="mt-4" onClick={() => handleAddField('skills')}>Add Category</Button>
            </div>

            <div className="mt-8">
              <h2 className="text-2xl font-semibold">Education</h2>
              {resumeData.education?.map((edu, index) => (
                <Card className="mt-4" key={index}>
                  <CardHeader className="grid justify-items-stretch">
                    <div>
                      <CardTitle>
                        <Input 
                          value={edu.institution || ''}
                          onChange={(e) => handleInputChange('education', 'institution', e.target.value, index)}
                          placeholder="Institution"
                        />
                      </CardTitle>
                      <CardDescription>
                        <Input 
                          value={edu.degree || ''}
                          onChange={(e) => handleInputChange('education', 'degree', e.target.value, index)}
                          placeholder="Degree"
                        />
                      </CardDescription>
                    </div>
                    <div className="text-sm text-muted-foreground dark:text-white">
                      <Input 
                        value={edu.years || ''}
                        onChange={(e) => handleInputChange('education', 'years', e.target.value, index)}
                        placeholder="Years"
                      />
                    </div>
                  </CardHeader>
                  <CardFooter className="grid gap-2">
                    <Button variant="destructive" onClick={() => handleDeleteField('education', index)}>Delete</Button>
                  </CardFooter>
                </Card>
              ))}
              <Button variant="secondary" className="mt-4" onClick={() => handleAddField('education')}>Add Education</Button>
            </div>

            <div className="mt-8">
              <h2 className="text-2xl font-semibold">Achievement</h2>
              {resumeData.achievement && (
                <Card className="mt-4">
                  <CardHeader className="grid justify-items-stretch">
                    <div>
                      <CardTitle>
                        <Input 
                          value={resumeData.achievement.title || ''}
                          onChange={(e) => handleInputChange('achievement', 'title', e.target.value)}
                          placeholder="Title"
                        />
                      </CardTitle>
                      <CardDescription>
                        <Textarea 
                          value={resumeData.achievement.description || ''}
                          onChange={(e) => handleInputChange('achievement', 'description', e.target.value)}
                          placeholder="Description"
                          className="min-h-[100px]"
                        />
                      </CardDescription>
                    </div>
                  </CardHeader>
                  <CardFooter className="grid gap-2">
                    <Button variant="destructive" onClick={() => handleDeleteField('achievement')}>Delete</Button>
                  </CardFooter>
                </Card>
              )}
              {!resumeData.achievement && (
                <Button variant="secondary" className="mt-4" onClick={() => handleAddField('achievement')}>Add Achievement</Button>
              )}
            </div>
          </div>
          <div className="w-full md:w-1/2">
            <h1 className="text-3xl font-bold">Preview</h1>
            <div id="resume" className="mt-8">
              <Resume {...resumeData} />
            </div>
            <Button variant="primary" className="mt-4" onClick={handleDownload}>Download PDF</Button>
          </div>
        </div>
      </main>
    </div>
  )
}


function FilePenIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22h6a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v10" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10.4 12.6a2 2 0 1 1 3 3L8 21l-4 1 1-4Z" />
    </svg>
  );
}

function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18M6 6l12 12" />
    </svg>
  );
}
