/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0R7r6LUIwnZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import React from 'react';
import Link from 'next/link';

export function LandingPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-white via-blue-100 to-purple-200 p-8">
      <div className="max-w-6xl mx-auto">
        <div className="bg-white rounded-lg shadow-lg p-8 mb-16 flex">
          <div className="w-1/2 pr-8">
            <h1 className="text-3xl font-bold text-gray-800 mb-8">Let's build your CV together</h1>
            <form className="space-y-6">
              <div className="grid grid-cols-2 gap-4">
                <input type="text" placeholder="First name" className="w-full p-2 border rounded" />
                <input type="text" placeholder="Surname" className="w-full p-2 border rounded" />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <input type="tel" placeholder="Mobile" className="w-full p-2 border rounded" />
                <input type="email" placeholder="Email" className="w-full p-2 border rounded" />
              </div>
              <div className="text-center font-bold text-gray-500">OR</div>
              <input
                type="text"
                placeholder="Paste your LinkedIn URL here for autofill"
                className="w-full p-2 border rounded"
              />
              <div className="flex justify-between mt-4">
                <button className="px-6 py-2 bg-gray-200 text-gray-800 rounded-full">Back</button>
              <Link href="/editor">
                <button className="px-6 py-2 bg-gray-800 text-white rounded-full" >
                  Continue
                </button>
              </Link>
              </div>
            </form>
          </div>
          <div className="w-1/2 pl-8">
            <div className="bg-gray-100 rounded-lg p-4 h-96 mb-4">
              {/* Placeholder for CV preview */}
              <img src="/cv-preview.png" alt="CV Preview" className="w-full h-full object-contain" />
            </div>
            <div className="flex justify-between items-center">
              <button className="p-2 border rounded-full">
                <ArrowLeftIcon className="h-6 w-6" />
              </button>
              <div className="flex space-x-2">
                {[...Array(7)].map((_, i) => (
                  <span key={i} className="w-2 h-2 bg-gray-300 rounded-full" />
                ))}
              </div>
              <button className="p-2 border rounded-full">
                <ArrowRightIcon className="h-6 w-6" />
              </button>
            </div>
          </div>
        </div>

        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold text-gray-800 mb-8">Build your cv_final with us</h2>
          <div className="flex justify-center space-x-8">
            {[
              { icon: FileIcon, title: 'State of the art templates' },
              { icon: SparkleIcon, title: 'AI assisted journey' },
              { icon: StarIcon, title: 'ATS friendly CV\'s' },
            ].map(({ icon: Icon, title }, index) => (
              <div key={index} className="bg-white rounded-lg shadow-lg p-6 w-64 flex flex-col items-center">
                <Icon className="w-16 h-16 text-gray-400 mb-4" />
                <p className="text-center font-semibold">{title}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}


// Keep the existing icon components (ArrowLeftIcon, ArrowRightIcon, FileIcon, SparkleIcon, StarIcon) as they are.

function ArrowLeftIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  )
}


function ArrowRightIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function FacebookIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function FileIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
    </svg>
  )
}


function LinkedinIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function SparkleIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z" />
    </svg>
  )
}


function StarIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function TwitterIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function XIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
