/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Qxdufs8rH8J
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent,
} from "@ui/components/ui/collapsible";

export function accordion() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="space-y-6">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
            Frequently Asked Questions
          </h2>
          <div className="space-y-4">
            <Collapsible>
              <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-muted px-4 py-3 text-left text-lg font-medium transition-colors hover:bg-muted-foreground/10 focus:outline-none focus-visible:ring focus-visible:ring-primary focus-visible:ring-opacity-75 [&[data-state=open]>svg]:rotate-180">
                <span>What is the pricing structure?</span>
                <ChevronDownIcon className="h-5 w-5 transition-transform" />
              </CollapsibleTrigger>
              <CollapsibleContent className="px-4 pt-4 pb-6 text-muted-foreground">
                <p>
                  Our pricing is based on the number of users and the features
                  you need. We offer a range of plans to fit your budget and
                  requirements. You can check our pricing page for more details
                  or contact us for a custom quote.
                </p>
              </CollapsibleContent>
            </Collapsible>
            <Collapsible>
              <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-muted px-4 py-3 text-left text-lg font-medium transition-colors hover:bg-muted-foreground/10 focus:outline-none focus-visible:ring focus-visible:ring-primary focus-visible:ring-opacity-75 [&[data-state=open]>svg]:rotate-180">
                <span>How do I get started?</span>
                <ChevronDownIcon className="h-5 w-5 transition-transform" />
              </CollapsibleTrigger>
              <CollapsibleContent className="px-4 pt-4 pb-6 text-muted-foreground">
                <p>
                  Getting started is easy! Simply sign up on our website and
                  follow the guided onboarding process. Our team is also
                  available to help you get set up and answer any questions you
                  might have.
                </p>
              </CollapsibleContent>
            </Collapsible>
            <Collapsible>
              <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-muted px-4 py-3 text-left text-lg font-medium transition-colors hover:bg-muted-foreground/10 focus:outline-none focus-visible:ring focus-visible:ring-primary focus-visible:ring-opacity-75 [&[data-state=open]>svg]:rotate-180">
                <span>What kind of support do you offer?</span>
                <ChevronDownIcon className="h-5 w-5 transition-transform" />
              </CollapsibleTrigger>
              <CollapsibleContent className="px-4 pt-4 pb-6 text-muted-foreground">
                <p>
                  We offer a range of support options, including 24/7 email
                  support, a comprehensive knowledge base, and access to our
                  team of experts. We're committed to ensuring your success and
                  providing the resources you need to get the most out of our
                  platform.
                </p>
              </CollapsibleContent>
            </Collapsible>
            <Collapsible>
              <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-muted px-4 py-3 text-left text-lg font-medium transition-colors hover:bg-muted-foreground/10 focus:outline-none focus-visible:ring focus-visible:ring-primary focus-visible:ring-opacity-75 [&[data-state=open]>svg]:rotate-180">
                <span>Do you offer any integrations?</span>
                <ChevronDownIcon className="h-5 w-5 transition-transform" />
              </CollapsibleTrigger>
              <CollapsibleContent className="px-4 pt-4 pb-6 text-muted-foreground">
                <p>
                  Yes, we offer a wide range of integrations with popular tools
                  and platforms, including CRM, project management, and
                  analytics tools. Our flexible API also allows you to build
                  custom integrations to fit your specific needs.
                </p>
              </CollapsibleContent>
            </Collapsible>
            <Collapsible>
              <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-muted px-4 py-3 text-left text-lg font-medium transition-colors hover:bg-muted-foreground/10 focus:outline-none focus-visible:ring focus-visible:ring-primary focus-visible:ring-opacity-75 [&[data-state=open]>svg]:rotate-180">
                <span>How secure is your platform?</span>
                <ChevronDownIcon className="h-5 w-5 transition-transform" />
              </CollapsibleTrigger>
              <CollapsibleContent className="px-4 pt-4 pb-6 text-muted-foreground">
                <p>
                  Security is a top priority for us. Our platform is built with
                  industry-leading security standards and practices, including
                  end-to-end encryption, multi-factor authentication, and
                  regular security audits. We also maintain strict compliance
                  with relevant data privacy regulations.
                </p>
              </CollapsibleContent>
            </Collapsible>
          </div>
        </div>
      </div>
    </section>
  );
}

function ChevronDownIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  );
}
