/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Oc15uN0qkQK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@ui/components/ui/card"
import Link from "next/link"

export function topic-card() {
  return (
    <div className="container mx-auto py-12 px-4 md:px-6">
      <div className="grid gap-8 md:gap-12">
        <Card className="bg-primary text-primary-foreground p-8 md:p-12 rounded-lg shadow-lg">
          <div className="flex flex-col items-start gap-4">
            <div className="inline-block rounded-lg bg-primary-foreground/20 px-3 py-1 text-sm font-medium">
              Featured
            </div>
            <h2 className="text-3xl md:text-4xl font-bold">Unlock the Power of Automation</h2>
            <p className="text-lg md:text-xl text-primary-foreground/80">
              Streamline your workflows and boost productivity with our cutting-edge automation tools.
            </p>
            <Link
              href="#"
              className="inline-flex items-center justify-center rounded-md bg-primary-foreground px-6 py-3 text-sm font-medium shadow-sm transition-colors hover:bg-primary-foreground/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
              prefetch={false}
            >
              Learn More
            </Link>
          </div>
        </Card>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8">
          <Card className="bg-background p-6 rounded-lg shadow-lg">
            <div className="flex flex-col items-start gap-4">
              <LayersIcon className="w-8 h-8 text-primary" />
              <h3 className="text-xl font-bold">Workflow Automation</h3>
              <p className="text-muted-foreground">Streamline your business processes and eliminate manual tasks.</p>
              <Link
                href="#"
                className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                prefetch={false}
              >
                Explore
              </Link>
            </div>
          </Card>
          <Card className="bg-background p-6 rounded-lg shadow-lg">
            <div className="flex flex-col items-start gap-4">
              <BoltIcon className="w-8 h-8 text-primary" />
              <h3 className="text-xl font-bold">Intelligent Triggers</h3>
              <p className="text-muted-foreground">Automate your workflows based on real-time events and triggers.</p>
              <Link
                href="#"
                className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                prefetch={false}
              >
                Explore
              </Link>
            </div>
          </Card>
          <Card className="bg-background p-6 rounded-lg shadow-lg">
            <div className="flex flex-col items-start gap-4">
              <CogIcon className="w-8 h-8 text-primary" />
              <h3 className="text-xl font-bold">Customizable Integrations</h3>
              <p className="text-muted-foreground">
                Connect your favorite tools and services with our flexible integrations.
              </p>
              <Link
                href="#"
                className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                prefetch={false}
              >
                Explore
              </Link>
            </div>
          </Card>
        </div>
      </div>
    </div>
  )
}

function BoltIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
      <circle cx="12" cy="12" r="4" />
    </svg>
  )
}


function CogIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20a8 8 0 1 0 0-16 8 8 0 0 0 0 16Z" />
      <path d="M12 14a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z" />
      <path d="M12 2v2" />
      <path d="M12 22v-2" />
      <path d="m17 20.66-1-1.73" />
      <path d="M11 10.27 7 3.34" />
      <path d="m20.66 17-1.73-1" />
      <path d="m3.34 7 1.73 1" />
      <path d="M14 12h8" />
      <path d="M2 12h2" />
      <path d="m20.66 7-1.73 1" />
      <path d="m3.34 17 1.73-1" />
      <path d="m17 3.34-1 1.73" />
      <path d="m11 13.73-4 6.93" />
    </svg>
  )
}


function LayersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z" />
      <path d="m22 17.65-9.17 4.16a2 2 0 0 1-1.66 0L2 17.65" />
      <path d="m22 12.65-9.17 4.16a2 2 0 0 1-1.66 0L2 12.65" />
    </svg>
  )
}
