name: Deploy to GCP

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  INSTANCE_GROUP: ${{ secrets.GCP_INSTANCE_GROUP }}
  ZONE: ${{ secrets.GCP_ZONE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Deploy to VM
        run: |
          gcloud compute instance-groups list-instances ${{ secrets.GCP_INSTANCE_GROUP }} \
            --zone ${{ secrets.GCP_ZONE }} \
            --format='get(instance)' | while read instance; do
            gcloud compute ssh $instance --zone ${{ secrets.GCP_ZONE }} --command '
              cd resume-build && \
              sudo docker system prune -a -f && \
              sudo docker-compose down && \
              git checkout master && \
              git pull origin master && \
              sudo docker-compose up --build -d
            '
          done
