name: Deploy to GCP

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  INSTANCE_GROUP: ${{ secrets.GCP_INSTANCE_GROUP }}
  ZONE: ${{ secrets.GCP_ZONE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to VM
        run: |
          gcloud compute instance-groups list-instances ${{ secrets.GCP_INSTANCE_GROUP }} \
            --zone ${{ secrets.GCP_ZONE }} \
            --format='get(instance)' | while read instance; do
            gcloud compute ssh $instance --zone ${{ secrets.GCP_ZONE }} --command '
              cd resume-build && \
              sudo docker system prune -a -f && \
              sudo docker-compose down && \
              git checkout master && \
              git pull origin master && \
              sudo docker-compose up --build -d
            '
          done
