name: Deploy to GCP

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  INSTANCE_GROUP: ${{ secrets.GCP_INSTANCE_GROUP }}
  ZONE: ${{ secrets.GCP_ZONE }}
  DOCKERHUB_USERNAME: yashs3324
  DOCKER_IMAGE_NAME: finalcv
  DOCKER_IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up environment variables for Next.js
        run: |
          echo "RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }}" >> apps/docs/.env
          echo "NEXT_PUBLIC_RAZORPAY_KEY_ID=${{ secrets.NEXT_PUBLIC_RAZORPAY_KEY_ID }}" >> apps/docs/.env
          echo "RAZORPAY_KEY_SECRET=${{ secrets.RAZORPAY_KEY_SECRET }}" >> apps/docs/.env

      - name: Build Docker image
        run: |
          docker build --build-arg RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }} \
                      --build-arg NEXT_PUBLIC_RAZORPAY_KEY_ID=${{ secrets.NEXT_PUBLIC_RAZORPAY_KEY_ID }} \
                      --build-arg RAZORPAY_KEY_SECRET=${{ secrets.RAZORPAY_KEY_SECRET }} \
                      -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} .

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username ${{ env.DOCKERHUB_USERNAME }} --password-stdin
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/google_compute_engine
          echo "${{ secrets.GCP_SSH_PUBLIC_KEY }}" > ~/.ssh/google_compute_engine.pub
          chmod 600 ~/.ssh/google_compute_engine
          chmod 600 ~/.ssh/google_compute_engine.pub

      - name: Deploy to VM instances
        run: |
          instances=$(gcloud compute instance-groups list-instances ${{ env.INSTANCE_GROUP }} \
            --zone ${{ env.ZONE }} \
            --format='get(instance)')

          for instance in $instances; do
            echo "Deploying to instance: $instance"
            
            # Wait for SSH to be available
            gcloud compute ssh --quiet $instance \
              --zone ${{ env.ZONE }} \
              --command "exit" \
              --ssh-key-file=~/.ssh/google_compute_engine
            
            # Pull latest image and restart containers
            gcloud compute ssh $instance \
              --zone ${{ env.ZONE }} \
              --ssh-key-file=~/.ssh/google_compute_engine \
              --command '
                cd resume-build && \
                sudo docker pull ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} && \
                sudo docker-compose down && \
                sudo docker system prune -af && \
                sudo docker-compose up -d
              '
            
            echo "Deployment completed for instance: $instance"
          done
